version: "2.1"

services:

  db:
    container_name: projectMongo
    image: mongo:latest
    ports:
      - 3300:27017
    environment: 
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
        MONGO_INITDB_DATABASE: oregon-wines
    volumes:
      - testMongo:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:latest
    container_name: sawtooth-settings-tp-default
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  tp:
    container_name: transaction-processor
    image: paynemi/tranproc:1.0
    expose:
      - 4004
    environment:
      URL: tcp://sawtooth-validator-default:4004
    volumes:
      - ./:/code
    
  client1:
    container_name: wineryClient
    build:
      context: ./client
    expose: 
      - 8080
    ports:
        - 8080:8080
    environment: 
      MONGO_HOST: projectMongo
      MONGO_PORT: 27017
      MONGO_USER: winery
      MONGO_PASSWORD: pass
      MONGO_DB_NAME: oregon-wines
      REST_API: sawtooth-rest-api-default
    volumes:
      - ./:/client1
    
  client2:
    container_name: customerClient
    build:
      context: ./custClient
    expose: 
      - 3000
    ports:
        - 3000:3000
    environment: 
      MONGO_HOST: projectMongo
      MONGO_PORT: 27017
      MONGO_USER: customer
      MONGO_PASSWORD: pass
      MONGO_DB_NAME: oregon-wines
      REST_API: sawtooth-rest-api-default
    volumes:
      - ./:/client2

  validator:
    image: hyperledger/sawtooth-validator:latest
    container_name: sawtooth-validator-default
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:latest
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust -C tcp://validator:5050

  rest-api:
    image: hyperledger/sawtooth-rest-api:latest
    container_name: sawtooth-rest-api-default
    ports:
      - "8008:8008"
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -C tcp://validator:4004 --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-shell:latest
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api
    entrypoint: "bash -c \"\
        sawtooth keygen && \
        tail -f /dev/null \
        \""

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: swagger-ui
    ports:
      - "8009:8080"
    environment:
      SWAGGER_JSON: /tmp/openapi.yaml
    command: "sh -c \"\
        wget \
          -q -O /tmp/openapi.yaml \
          https://raw.githubusercontent.com/hyperledger/sawtooth-core/master/rest_api/openapi.yaml && \
        /usr/share/nginx/run.sh \
        \""

volumes:
    testMongo:
